### ISSUE TITLE
New idea for admin panel

### ISSUE THREAD

**Issue by kosc** [zenwalker/django-micro#11]
What if we will right:
```python
configure(locals(), admin_on='admin')
```
instead of:
```python
configure(locals(), django_admin=True)
```

So, in that case we will make it even more easy to enable admin and add route.

**Comment by maxpoletaev** [comment]
I don’t think it’s a good idea to make any api changes after release :)

**Comment by kosc** [comment]
Ok, but what if we implement this feature in 2.x release?

**Comment by maxpoletaev** [comment]
Look, I don’t really think that any change here worth it. We’ve already reduced a significant amount of lines by adding that shortcut. Saving one more line is not a big deal.
