### ISSUE TITLE
ERROR:Command errored out with exit status 1: python setup.py egg_i

### ISSUE THREAD

**Issue by cai1234cai** [zenwalker/django-micro#19]
When I use command 'pip install django-micro' to install this library in windows PowerShell.
This error has occurred：
`ERROR:Command` errored out with exit status 1: python setup.py egg_i`

![29251564150083_ pic_hd](https://user-images.githubusercontent.com/26889842/61988571-8e712800-b055-11e9-83e7-e834c7b5c518.jpg)

But ,when I remove the readme line in setup.py, I can install it.

**Comment by cai1234cai** [comment]
long_description=read('README.rst'),

**Comment by maxpoletaev** [comment]
Should be fixed in https://github.com/zenwalker/django-micro/pull/18
