### ISSUE TITLE
Add admin panel

### ISSUE THREAD

**Issue by kosc** [zenwalker/django-micro#8]
I think it would be great to add lightweight integration of admin panel.

**Comment by maxpoletaev** [comment]
What do you mean by “lightweight”? There is an [example](https://github.com/zenwalker/django-micro/blob/master/example/app.py#L105) of the use django.admin in the demo app.

**Comment by kosc** [comment]
I don't think it's lightweight - we need also to add some installed apps for admin, some middlewares and maybe i've miss something else. So, how many lines of code I should add in my app https://github.com/kosc/chatquotes/blob/master/app.py to enable django admin?

**Comment by maxpoletaev** [comment]
OK, I got the point. Maybe I should add the parameter like `configure(locals(), enable_admin=True)` that automatically includes all the required apps and middleware and adds the path to the admin interface to `urlpatterns`. Unfortunately, I don’t have enough time to add this feature at the moment. If you’d like to implement this, I’ll be glad to see your PR.

**Comment by kosc** [comment]
Please look at my PR: https://github.com/zenwalker/django-micro/pull/9

**Comment by maxpoletaev** [comment]
Released in 1.6.0 but I’ve renamed the argument to `django_admin=True`.
